# Generated by Django 2.0.6 on 2019-02-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people_master',
            name='mailstop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='collection.mailstops_master'),
        ),
    ]
