# Generated by Django 2.0.6 on 2019-02-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190217_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages_master',
            name='mailstop',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
