# Generated by Django 2.0.6 on 2019-02-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190224_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_master',
            name='mailstop',
        ),
    ]
