# Generated by Django 2.0.13 on 2019-03-05 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
